### ISSUE TITLE
Add total number of connected minions

### ISSUE THREAD

**Issue by julioz** [kpetremann/salt-exporter#29]
On every scrape, the exporter should include a gauge metric with the number of connected minions to that master node.
This way we can keep track of new minions connected, but more importantly, when minions disappear.

**Comment by kpetremann** [comment]
hello @julioz,

What about counting the number of minion using `salt_responses_total` metric?

The exporter is passive, it only watches the event queue. So I don't see how we could know that a minion disappeared, except if your are sending requesting targeting all minions. But if you do, the `salt_responses_total` would do the trick.

Note: where I work, we use another simple active exporter only to "ping" our minions (not open-source):
* It sends a `test.ping` request to all minions via the API.
* Then it parses the results to count number of responding and not responding minions.
But this is not always reliable depending on your targets workload: sometimes the minion does not respond to test.ping before the timeout because it was doing something else.

**Comment by julioz** [comment]
> The exporter is passive, it only watches the event queue

Got it. Is your intent to keep it passive-only, or is `salt-exporter` intended to grow for "all things salt". If the latter, I'd imagine a `salt-run manage.alived` could be a good way to count "up" minions without sending `test.ping` commands that could hang.

**Comment by julioz** [comment]
> Note: where I work, we use another simple active exporter only to "ping" our minions (not open-source):

We ended up implementing something similar, but based on a homegrown active salt exporter. Feel free to close this issue if there are no plans to implement similarly in this exporter 👍

**Comment by kpetremann** [comment]
ok great :) thanks for the feedback.
I think this is the best approach for now.

I'll close the issue.
If I plan to add this kind of feature (Salt API client based metrics) in the future, I'll mention this issue.

**Comment by kpetremann** [comment]
hello @julioz,

The PR #57 might interest you (available in v0.9.0).
